baseURL = "https://profetia.github.io/u/"
languageCode = "en-us"
title = "Union of Progressive Peoples"
theme = "archie"
copyright = "© Linshu Yang"

pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
paginate = 4

[markup.goldmark.renderer]
unsafe = true

[params]
favicon = "favicon.ico"
og_image = "images/upp.webp"
# mode = "auto"
mode = "toggle"
useCDN = true
subtitle = "Unity, Progress, People"
description = "Unity, Progress, People"

[[params.social]]
name = "Mail"
icon = "mail"
url = "mailto:yanglsh@shanghaitech.edu.cn"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/athul/archie"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/linshu-yang-3398a425a/"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
